### PR TITLE
Use `ember-auto-import`

### LINKED ISSUE #14: Does not work with ember-cli 3.5.0-beta.2
I'm hitting this error:

`ENOENT: no such file or directory, open '/var/folders/tf/h_tyhd41165d978ps4hgc5wc0000gn/T/broccoli-67565lS9lkUhGsKi/out-453-broccoli_debug_debug_5_vendor_js/vendor/-ember-date-fns-bundle.js'`

I believe this is because ember-cli now tries to use your system's `temp` folder, rather than creating a `tmp` folder.

### PR DESCRIPTION
**Pull request by btecu**
Update `ember-cli` and dependencies.
Use `ember-auto-import` instead of custom `webpack`. Closes #14.

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
@btecu is there a way to exclude/include files with this? I'd like to get tree shaking, if we can.

**Comment by btecu** [comment]
@rwwagner90 it's automatic. By default only the two helpers and their dependencies are bundled. If you `import { someFunction } ...` it will also bundle that one.

**Comment by btecu** [comment]
Ping @oskarrough.

**Comment by oskarrough** [comment]
@btecu hey! This looks great. I haven't been able to test it yet but if you say go, let's go?

Also, I'd be happy to add you to the repository if you're interested.

**Comment by btecu** [comment]
I've checked whether it brings the library by just looking at the payload size. It would be nice to have @rwwagner90 confirm that it works as intended.

@rwwagner90 can you confirm it only brings the two included helpers and any other function that you `import`? Easiest is by looking at the `ember b --prod` numbers.

**Comment by RobbieTheWagner** [comment]
@btecu I think if you tested adding some imports and the bundle size went up, that sounds like it is working.

**Comment by btecu** [comment]
Actually, it appears that the size increase was not related and dynamic import doesn't work. I'll look into it.

File: blueprints/ember-date-fns/index.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/* eslint-env node */
+
+module.exports = {
+  description: 'Add `date-fns` to the consumer application',
+
+  afterInstall() {
+    return this.addPackagesToProject([
+      { name: 'date-fns', target: '^1.30.1' },
```
Comment (RobbieTheWagner) [inline blueprints/ember-date-fns/index.js:8]: Shouldn't this be a dep of `ember-date-fns` rather than added directly to the app? If we add it to the app, why would people use this addon?

**Comment by btecu** [comment]
I've update the pull request to include a blueprint that brings in `date-fns` to the host application.

Looking at the size and testing import, it confirms that it's brought in when using `import` directly.

Base size:
```
 - dist//assets/dates-977e2cf828e86940ef0ba744dc422ee2.js: 5.78 KB (1.48 KB gzipped)
 - dist//assets/vendor-c1df3229b6849c167112e482697fd506.js: 752.14 KB (196.4 KB gzipped)
```

After adding `import differenceInCalendarDays from 'date-fns/difference_in_calendar_days';`:
```
 - dist//assets/dates-a6dc200b7c08024ea63ea02ebf426b15.js: 5.84 KB (1.51 KB gzipped)
 - dist//assets/vendor-32d7c461add8ef7e0f8e2d86f4d997d3.js: 752.21 KB (196.41 KB gzipped)
```

Should be ready for merging after you review the last commit.

File: blueprints/ember-date-fns/index.js (hunk 1 above)
Comment (btecu) [reply blueprints/ember-date-fns/index.js:8]: For the base helpers, I suppose. `ember-auto-import` doesn't support that.

Here is some discussion about this with @ef4: https://github.com/ef4/ember-auto-import/issues/179

Comment (btecu) [reply blueprints/ember-date-fns/index.js:8]: @rwwagner90 Having `date-fns` just in the addon wouldn't bring much benefit anyway.
It would actually lock you on a specific version, so this is better anyway.

In addition, this way you can just use any extra helpers you might need without having to whitelist them in some configuration file.

Comment (RobbieTheWagner) [reply blueprints/ember-date-fns/index.js:8]: @btecu I think I would suggest deprecating this addon then, as it adds no benefits, and ember-auto-import should be used.

Comment (btecu) [reply blueprints/ember-date-fns/index.js:8]: @rwwagner90 The two helpers that it provides are used on most projects, so it does save us from creating those helpers on every single project.

Comment (RobbieTheWagner) [reply blueprints/ember-date-fns/index.js:8]: Ah, true.

**Comment by btecu** [comment]
@oskarrough Can we get this merged?

**Comment by oskarrough** [comment]
Happy to, thanks a lot!

**Comment by btecu** [comment]
Can we get a release too?

**Comment by oskarrough** [comment]
@btecu sorry for the wait.. especially considering your effort, but 0.5.0 is released now! If you'd like access to publish on npm let me know.
